"""Generate framework-native theme files from a brand summary so the
designer can drop them straight into a real project — not just look at
a screenshot.

  tailwind.config.js   — Tailwind config snippet with brand colours,
                         tonal ramp, and Google-Fonts wiring
  theme.ts             — Material UI v5 createTheme() with the same
                         palette and typography
  _brand-variables.scss — Bootstrap 5 SCSS override file (drop in
                         before bootstrap.scss to retune the kit)

Each function returns the file body as a UTF-8 string. They never
raise — missing brand fields fall back to sensible defaults so the
generated file is always valid syntax."""

from __future__ import annotations

from typing import Any


# ─────────────────────────────────────────────────────────────────
# Colour helpers
# ─────────────────────────────────────────────────────────────────
def _hex_to_rgb(hex_: str) -> tuple[int, int, int]:
    h = (hex_ or "").lstrip("#")
    if len(h) == 3:
        h = "".join(c * 2 for c in h)
    if len(h) != 6:
        return (0, 0, 0)
    try:
        return int(h[0:2], 16), int(h[2:4], 16), int(h[4:6], 16)
    except ValueError:
        return (0, 0, 0)


def _luminance(hex_: str) -> float:
    r, g, b = _hex_to_rgb(hex_)
    return (0.299 * r + 0.587 * g + 0.114 * b) / 255


def _contrast_text(hex_: str) -> str:
    return "#0F172A" if _luminance(hex_) > 0.6 else "#FFFFFF"


def _mix_with_white(hex_: str, t: float) -> str:
    r, g, b = _hex_to_rgb(hex_)
    return "#{:02X}{:02X}{:02X}".format(
        int(r + (255 - r) * t),
        int(g + (255 - g) * t),
        int(b + (255 - b) * t),
    )


def _mix_with_black(hex_: str, t: float) -> str:
    r, g, b = _hex_to_rgb(hex_)
    return "#{:02X}{:02X}{:02X}".format(
        int(r * (1 - t)),
        int(g * (1 - t)),
        int(b * (1 - t)),
    )


def _ramp(hex_: str) -> dict[int, str]:
    """Return a Tailwind-style 50→950 tonal ramp for a base hex."""
    return {
        50:  _mix_with_white(hex_, 0.92),
        100: _mix_with_white(hex_, 0.84),
        200: _mix_with_white(hex_, 0.66),
        300: _mix_with_white(hex_, 0.48),
        400: _mix_with_white(hex_, 0.24),
        500: hex_,
        600: _mix_with_black(hex_, 0.12),
        700: _mix_with_black(hex_, 0.24),
        800: _mix_with_black(hex_, 0.40),
        900: _mix_with_black(hex_, 0.55),
        950: _mix_with_black(hex_, 0.72),
    }


def _font_q(name: str) -> str:
    return (name or "Inter").strip().replace(" ", "+")


def _fallback_for(font_name: str, kind: str) -> str:
    """Reasonable CSS fallback stack for the brand's font."""
    if kind == "display":
        return "ui-serif, Georgia, serif" if (font_name or "").lower().endswith("serif") else "ui-sans-serif, system-ui, sans-serif"
    return "ui-sans-serif, system-ui, -apple-system, 'Segoe UI', Roboto, sans-serif"


# ─────────────────────────────────────────────────────────────────
# Tailwind config (tailwind.config.js — drop into a Tailwind v3 project)
# ─────────────────────────────────────────────────────────────────
def tailwind_config(brand: dict[str, Any]) -> str:
    name = brand.get("brand_name") or brand.get("domain") or "Brand"
    primary = (brand.get("primary_color") or "#0F172A").upper()
    secondary = (brand.get("secondary_color") or "#475569").upper()
    accent = (brand.get("accent_color") or primary).upper()
    surface = (brand.get("surface_color") or "#FFFFFF").upper()
    text_color = (brand.get("text_color") or "#0F172A").upper()
    display_font = brand.get("primary_font") or "Inter"
    body_font = brand.get("body_font") or display_font or "Inter"

    primary_ramp = _ramp(primary)
    secondary_ramp = _ramp(secondary)
    accent_ramp = _ramp(accent)

    def js_ramp(ramp: dict[int, str]) -> str:
        return ",\n          ".join(f"{k}: '{v}'" for k, v in ramp.items())

    display_fb = _fallback_for(display_font, "display")
    body_fb = _fallback_for(body_font, "body")

    return f"""// {name} — Tailwind config
// Auto-generated by project-neptune.
// Drop into a Tailwind v3 project alongside the @import line below.
//
//   <head>
//     <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family={_font_q(display_font)}:wght@500;700&family={_font_q(body_font)}:wght@400;500;700&display=swap" />
//   </head>
//
/** @type {{import('tailwindcss').Config}} */
module.exports = {{
  content: ['./src/**/*.{{js,jsx,ts,tsx,html}}'],
  theme: {{
    extend: {{
      colors: {{
        brand: {{
          {js_ramp(primary_ramp)},
          DEFAULT: '{primary}',
          contrast: '{_contrast_text(primary)}',
        }},
        secondary: {{
          {js_ramp(secondary_ramp)},
          DEFAULT: '{secondary}',
          contrast: '{_contrast_text(secondary)}',
        }},
        accent: {{
          {js_ramp(accent_ramp)},
          DEFAULT: '{accent}',
          contrast: '{_contrast_text(accent)}',
        }},
        surface: '{surface}',
        ink: '{text_color}',
      }},
      fontFamily: {{
        display: ['"{display_font}"', {display_fb!r}.split(',').map(s => s.trim().replace(/^['"]|['"]$/g, ''))],
        sans: ['"{body_font}"', {body_fb!r}.split(',').map(s => s.trim().replace(/^['"]|['"]$/g, ''))],
      }},
    }},
  }},
  plugins: [],
}};
"""


# ─────────────────────────────────────────────────────────────────
# Material UI v5 theme (theme.ts)
# ─────────────────────────────────────────────────────────────────
def mui_theme(brand: dict[str, Any]) -> str:
    name = brand.get("brand_name") or brand.get("domain") or "Brand"
    primary = (brand.get("primary_color") or "#0F172A").upper()
    secondary = (brand.get("secondary_color") or "#475569").upper()
    accent = (brand.get("accent_color") or primary).upper()
    surface = (brand.get("surface_color") or "#FFFFFF").upper()
    text_color = (brand.get("text_color") or "#0F172A").upper()
    display_font = brand.get("primary_font") or "Roboto"
    body_font = brand.get("body_font") or display_font or "Roboto"

    primary_dark = _mix_with_black(primary, 0.20)
    primary_light = _mix_with_white(primary, 0.30)
    secondary_dark = _mix_with_black(secondary, 0.20)
    secondary_light = _mix_with_white(secondary, 0.30)

    return f"""// {name} — Material UI v5 theme
// Auto-generated by project-neptune.
//
//   pnpm add @mui/material @emotion/react @emotion/styled
//   pnpm add @fontsource/{_font_q(body_font).lower()} @fontsource/{_font_q(display_font).lower()}
//
// import {{ ThemeProvider, createTheme }} from '@mui/material';
// import theme from './theme';
// <ThemeProvider theme={{theme}}>…</ThemeProvider>

import {{ createTheme }} from '@mui/material/styles';

const theme = createTheme({{
  palette: {{
    mode: '{"dark" if _luminance(surface) < 0.5 else "light"}',
    primary: {{
      main: '{primary}',
      dark: '{primary_dark}',
      light: '{primary_light}',
      contrastText: '{_contrast_text(primary)}',
    }},
    secondary: {{
      main: '{secondary}',
      dark: '{secondary_dark}',
      light: '{secondary_light}',
      contrastText: '{_contrast_text(secondary)}',
    }},
    info: {{ main: '{accent}', contrastText: '{_contrast_text(accent)}' }},
    background: {{ default: '{surface}', paper: '{surface}' }},
    text: {{ primary: '{text_color}' }},
  }},
  typography: {{
    fontFamily: '"{body_font}", "Roboto", system-ui, sans-serif',
    h1: {{ fontFamily: '"{display_font}", "Roboto", sans-serif', fontWeight: 700, letterSpacing: '-0.02em' }},
    h2: {{ fontFamily: '"{display_font}", "Roboto", sans-serif', fontWeight: 700, letterSpacing: '-0.015em' }},
    h3: {{ fontFamily: '"{display_font}", "Roboto", sans-serif', fontWeight: 700 }},
    h4: {{ fontFamily: '"{display_font}", "Roboto", sans-serif', fontWeight: 700 }},
    button: {{ fontWeight: 600, textTransform: 'none', letterSpacing: '0.02em' }},
  }},
  shape: {{ borderRadius: 10 }},
  components: {{
    MuiButton: {{
      styleOverrides: {{
        root: {{ borderRadius: 999, paddingInline: 22, paddingBlock: 9 }},
      }},
    }},
    MuiChip: {{
      styleOverrides: {{
        root: {{ borderRadius: 999, fontWeight: 500 }},
      }},
    }},
    MuiAppBar: {{
      styleOverrides: {{
        root: {{ boxShadow: '0 1px 0 rgba(0,0,0,.07), 0 2px 4px rgba(0,0,0,.05)' }},
      }},
    }},
  }},
}});

export default theme;
"""


# ─────────────────────────────────────────────────────────────────
# Bootstrap 5 SCSS overrides (_brand-variables.scss)
# ─────────────────────────────────────────────────────────────────
def bootstrap_variables(brand: dict[str, Any]) -> str:
    name = brand.get("brand_name") or brand.get("domain") or "Brand"
    primary = (brand.get("primary_color") or "#0F172A").upper()
    secondary = (brand.get("secondary_color") or "#475569").upper()
    accent = (brand.get("accent_color") or primary).upper()
    surface = (brand.get("surface_color") or "#FFFFFF").upper()
    text_color = (brand.get("text_color") or "#0F172A").upper()
    display_font = brand.get("primary_font") or "Inter"
    body_font = brand.get("body_font") or display_font or "Inter"

    return f"""// {name} — Bootstrap 5 brand variables
// Auto-generated by project-neptune.
//
// Drop this in BEFORE Bootstrap's variables so it overrides defaults:
//
//   @import "./brand-variables";
//   @import "bootstrap/scss/bootstrap";
//
// Or with CSS only (no SCSS): copy the :root {{ ... }} block at the
// bottom of this file into your stylesheet.

// ── Brand identity ──
$brand-primary:   {primary};
$brand-secondary: {secondary};
$brand-accent:    {accent};
$brand-surface:   {surface};
$brand-text:      {text_color};

// ── Bootstrap variable overrides ──
$primary:   $brand-primary;
$secondary: $brand-secondary;
$info:      $brand-accent;
$body-bg:   $brand-surface;
$body-color: $brand-text;

$link-color:       $brand-primary;
$link-hover-color: darken($brand-primary, 12%);

// Typography
$font-family-sans-serif: "{body_font}", system-ui, -apple-system, "Segoe UI", Roboto, sans-serif;
$headings-font-family:   "{display_font}", "{body_font}", system-ui, sans-serif;
$headings-font-weight:   700;
$headings-letter-spacing: -0.02em;

// Component tuning
$border-radius:    .5rem;
$border-radius-sm: .375rem;
$border-radius-lg: 1rem;
$btn-border-radius: 999px;
$btn-font-weight:  600;
$btn-padding-y:    .55rem;
$btn-padding-x:    1.4rem;

// ── CSS variables (use this block if you're NOT using SCSS) ──
:root {{
  --brand-primary:   {primary};
  --brand-secondary: {secondary};
  --brand-accent:    {accent};
  --brand-surface:   {surface};
  --brand-text:      {text_color};

  --bs-primary:      {primary};
  --bs-primary-rgb:  {", ".join(str(x) for x in _hex_to_rgb(primary))};
  --bs-link-color:   {primary};
  --bs-body-font-family:     "{body_font}", system-ui, sans-serif;
  --bs-headings-font-family: "{display_font}", "{body_font}", sans-serif;
}}
"""


__all__ = ["tailwind_config", "mui_theme", "bootstrap_variables"]
